$(document).ready(function(){
  $('#div1').click(function(){
    $('#text1').slideToggle("slow");
  });
  $('#div2').click(function(){
    $('#text2').slideToggle("slow");
  });
  $('#div3').click(function(){
    $('#text3').slideToggle("slow");
  });
});
